### ISSUE TITLE
[Device Request] OasisMist 1000S

### ISSUE THREAD

**Issue by vernlazaro** [pschroeder89/homebridge-levoit-humidifiers#51]
**Model number:** LUH-M101S-WUS

**Number of cool mist levels:**

**Number of warm mist levels:**

**Auto mode?** Yes

**Sleep mode?** Yes

**Night Light?**

**Any other features not listed above?**

**Comment by pschroeder89** [comment]
Hi @vernlazaro, does this model have High, Medium, and Low cool mist levels? Or are there more than that?
Also, can you post a screenshot of the VeSync App with the controls for the humidifier open?
Thanks!

**Comment by vernlazaro** [comment]
Hi pschroeder89,

It has Low-Med-High mist settings. I've also attached a screenshot of the controls.

![OasisMist 1000s](https://user-images.githubusercontent.com/123420904/214170632-27c86acf-4c4f-458c-86af-0a91d85fff0e.jpeg)

**Comment by pschroeder89** [comment]
`1.8.9-beta1` is published. Please give it a shot.

You should have a display toggle, sleep mode toggle, cool mist slider that goes from 0-9 (0 will turn it off), and an auto slider that goes from 40-80% (setting below and above those numbers will force them to 40 or 80).

**Comment by vernlazaro** [comment]
It's getting this error starting up the plugin:  [Levoit Humidifiers] Failed to updateInfo due to unreachable device: Cannot read properties of undefined (reading 'auto_target_humidity')

**Comment by pschroeder89** [comment]
Ah, this might be a more difficult device, then. I've published `1.8.9-beta2`. Before the error you see above, you should now see a text block that starts with `[UPDATE INFO DEBUG] `

Could you post that response? I don't think it will have any credentials or anything, but please double check first before posting. You can also DM me if that's easier

**Comment by vernlazaro** [comment]
Here you go:
[Levoit Humidifiers] Discovering devices...
[UPDATE INFO DEBUG] {"powerSwitch":1,"humidity":43,"targetHumidity":55,"virtualLevel":9,"mistLevel":3,"workMode":"auto","waterLacksState":0,"waterTankLifted":0,"autoStopSwitch":1,"autoStopState":0,"screenSwitch":1,"screenState":1,"scheduleCount":0,"timerRemain":0,"errorCode":0}
[1/23/2023, 6:54:39 PM] [Levoit Humidifiers] Failed to updateInfo due to unreachable device: Cannot read properties of undefined (reading 'auto_target_humidity')

**Comment by pschroeder89** [comment]
Thanks! They've changed a bunch of the fields 🤦🏼 . I will try to get this completed later tonight or tomorrow

**Comment by vernlazaro** [comment]
Thanks!

**Comment by pschroeder89** [comment]
I pushed beta3 with a fix for your first error message, but I don't think things will work 100%. I do think you should get past your original error message now. Could you let me know what the next error you see is, or which functionalities are broken? Thanks for the help!

**Comment by vernlazaro** [comment]
The error is gone but now there's this warning:   [homebridge-levoit-humidifiers] This plugin generated a warning from the characteristic 'Relative Humidity Humidifier Threshold': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
![levoit2](https://user-images.githubusercontent.com/123420904/214185349-9f4086ee-d53f-41ca-9207-9f21eae6621a.jpeg)

I've attached a screenshot of the accessories. Power on/off does not work.

**Comment by pschroeder89** [comment]
Ok beta4 has been pushed. I think the `'Relative Humidity Humidifier Threshold'` error might be resolved now, and you should see a `[TARGET HUMIDIDITY]: <number>` log now. 

As for power not working, I'm really hoping that the above error was causing the failure. There's a decent chance that Levoit changed the API command though. If that's the case, I won't be able to find the new command due to some recent security changes they made in the app, so we may not be able to support this model until someone figures out the new command.

Fingers crossed that it works now!

**Comment by vernlazaro** [comment]
There's a different warning this time. Here's the message with debug info. None of the controls work.

[Levoit Humidifiers] [DEBUG]: [DEVICE INFO] {"traceId":"1674562867328","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674562867328","code":0,"result":{"powerSwitch":1,"humidity":41,"targetHumidity":55,"virtualLevel":9,"mistLevel":3,"workMode":"auto","waterLacksState":0,"waterTankLifted":0,"autoStopSwitch":1,"autoStopState":0,"screenSwitch":1,"screenState":1,"scheduleCount":0,"timerRemain":0,"errorCode":0}}}

[1/24/2023, 7:22:51 AM] [homebridge-levoit-humidifiers] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.

**Comment by pschroeder89** [comment]
beta5 is published. The above error should be resolved.

For context, this model returns values in `camelCase`, while all other models return values in `snake_case`. I had missed the `virtualLevel` field, causing the cool mist slider accessory not to load and throw that error.

@vernlazaro There is a Discord server channel for this plugin if that's a simpler way to communicate for you:
1. Accept the invite https://discord.gg/homebridge-432663330281226270
2. Go to the channel https://discord.com/channels/432663330281226270/1055705874460594247

**Comment by vernlazaro** [comment]
The warning message is gone but the controls still don't work. Here are the debug logs trying to turn several on/off options.

[TARGET HUMIDIDITY]: 55
[1/24/2023, 5:53:28 PM] [Levoit Humidifiers] Setting Display to false
[1/24/2023, 5:53:28 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setDisplay to Humidifier with ({"state":false})...
[1/24/2023, 5:53:28 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setDisplay to Humidifier with ({"state":false})! Response: {"traceId":"1674600808202","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600808202","code":11000000}}
[1/24/2023, 5:53:30 PM] [Levoit Humidifiers] [DEBUG]: [GET DEVICE INFO] Getting device info...
[1/24/2023, 5:53:30 PM] [Levoit Humidifiers] [DEBUG]: [DEVICE INFO] {"traceId":"1674600810027","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600810027","code":0,"result":{"powerSwitch":1,"humidity":42,"targetHumidity":55,"virtualLevel":9,"mistLevel":3,"workMode":"auto","waterLacksState":0,"waterTankLifted":0,"autoStopSwitch":1,"autoStopState":0,"screenSwitch":1,"screenState":1,"scheduleCount":0,"timerRemain":0,"errorCode":0}}}
[TARGET HUMIDIDITY]: 55
[1/24/2023, 5:53:32 PM] [Levoit Humidifiers] Setting Display to false
[1/24/2023, 5:53:32 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setDisplay to Humidifier with ({"state":false})...
[1/24/2023, 5:53:32 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setDisplay to Humidifier with ({"state":false})! Response: {"traceId":"1674600812482","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600812482","code":11000000}}
[1/24/2023, 5:53:34 PM] [Levoit Humidifiers] Setting Display to true
[1/24/2023, 5:53:34 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setDisplay to Humidifier with ({"state":true})...
[1/24/2023, 5:53:34 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setDisplay to Humidifier with ({"state":true})! Response: {"traceId":"1674600814112","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600814112","code":11000000}}
[TARGET HUMIDIDITY]: 55
[1/24/2023, 5:53:36 PM] [Levoit Humidifiers] [DEBUG]: [GET DEVICE INFO] Getting device info...
[1/24/2023, 5:53:36 PM] [Levoit Humidifiers] [DEBUG]: [DEVICE INFO] {"traceId":"1674600816021","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600816021","code":0,"result":{"powerSwitch":1,"humidity":42,"targetHumidity":55,"virtualLevel":9,"mistLevel":3,"workMode":"auto","waterLacksState":0,"waterTankLifted":0,"autoStopSwitch":1,"autoStopState":0,"screenSwitch":1,"screenState":1,"scheduleCount":0,"timerRemain":0,"errorCode":0}}}
[TARGET HUMIDIDITY]: 55
[1/24/2023, 5:53:38 PM] [Levoit Humidifiers] Setting Power to false
[1/24/2023, 5:53:38 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setSwitch to Humidifier with ({"enabled":false,"id":0})...
[1/24/2023, 5:53:38 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setSwitch to Humidifier with ({"enabled":false,"id":0})! Response: {"traceId":"1674600818027","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600818027","code":11000000}}
[TARGET HUMIDIDITY]: 0
[1/24/2023, 5:53:46 PM] [Levoit Humidifiers] Setting Display to false
[1/24/2023, 5:53:46 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setDisplay to Humidifier with ({"state":false})...
[1/24/2023, 5:53:46 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setDisplay to Humidifier with ({"state":false})! Response: {"traceId":"1674600826088","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600826088","code":11000000}}
[1/24/2023, 5:53:46 PM] [Levoit Humidifiers] [DEBUG]: [GET DEVICE INFO] Getting device info...
[1/24/2023, 5:53:46 PM] [Levoit Humidifiers] [DEBUG]: [DEVICE INFO] {"traceId":"1674600826264","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600826264","code":0,"result":{"powerSwitch":1,"humidity":46,"targetHumidity":55,"virtualLevel":5,"mistLevel":2,"workMode":"auto","waterLacksState":0,"waterTankLifted":0,"autoStopSwitch":1,"autoStopState":0,"screenSwitch":1,"screenState":1,"scheduleCount":0,"timerRemain":0,"errorCode":0}}}
[TARGET HUMIDIDITY]: 55
[TARGET HUMIDIDITY]: 55
[1/24/2023, 5:54:43 PM] [Levoit Humidifiers] [DEBUG]: [GET DEVICE INFO] Getting device info...
[1/24/2023, 5:54:44 PM] [Levoit Humidifiers] [DEBUG]: [DEVICE INFO] {"traceId":"1674600883865","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600883865","code":0,"result":{"powerSwitch":1,"humidity":43,"targetHumidity":55,"virtualLevel":9,"mistLevel":3,"workMode":"auto","waterLacksState":0,"waterTankLifted":0,"autoStopSwitch":1,"autoStopState":0,"screenSwitch":1,"screenState":1,"scheduleCount":0,"timerRemain":0,"errorCode":0}}}
[TARGET HUMIDIDITY]: 55
[1/24/2023, 5:55:02 PM] [Levoit Humidifiers] Setting Display to false
[1/24/2023, 5:55:02 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setDisplay to Humidifier with ({"state":false})...
[1/24/2023, 5:55:02 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setDisplay to Humidifier with ({"state":false})! Response: {"traceId":"1674600902701","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600902701","code":11000000}}
[1/24/2023, 5:55:08 PM] [Levoit Humidifiers] Setting Power to false
[1/24/2023, 5:55:08 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setSwitch to Humidifier with ({"enabled":false,"id":0})...
[1/24/2023, 5:55:08 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setSwitch to Humidifier with ({"enabled":false,"id":0})! Response: {"traceId":"1674600908687","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600908687","code":11000000}}
[1/24/2023, 5:55:17 PM] [Levoit Humidifiers] Setting Display to true
[1/24/2023, 5:55:17 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setDisplay to Humidifier with ({"state":true})...
[1/24/2023, 5:55:17 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setDisplay to Humidifier with ({"state":true})! Response: {"traceId":"1674600917099","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600917099","code":11000000}}
[1/24/2023, 5:55:21 PM] [Levoit Humidifiers] Changing Mode to sleep
[1/24/2023, 5:55:21 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setHumidityMode to Humidifier with ({"mode":"sleep"})...
[1/24/2023, 5:55:21 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setHumidityMode to Humidifier with ({"mode":"sleep"})! Response: {"traceId":"1674600921017","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600921017","code":11000000}}
[1/24/2023, 5:55:39 PM] [Levoit Humidifiers] Setting Power to true
[1/24/2023, 5:55:39 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setSwitch to Humidifier with ({"enabled":true,"id":0})...
[1/24/2023, 5:55:39 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setSwitch to Humidifier with ({"enabled":true,"id":0})! Response: {"traceId":"1674600939202","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674600939202","code":11000000}}

**Comment by pschroeder89** [comment]
The `11000000` error indicates that the payload is wrong. So your humidifier expects different command structures than the other model humidifiers. Unfortunately, users have been blocked from "catching" the correct command structures, so there's not much else I can do at the moment. I expect someone to figure them out down the line, maybe in the python project here: https://github.com/webdjoe/pyvesync

I'll leave this bug open and will check other projects for updates periodically.

Sorry and thanks for helping debug!

**Comment by vernlazaro** [comment]
Ah, I see. Thanks for trying and for your patience.

**Comment by pschroeder89** [comment]
@vernlazaro thanks for the donation! I had an idea of something to try. I've pushed `1.8.9-beta.6`, where we try sending a different command when turning the device on. Please update and try turning the humidifier on / off. 

Please also post the logs for `Setting Power`, they should look like

```
[26/01/2023, 11:01:13] [Levoit Humidifiers] Setting Power to 1
```

If this doesn't work and returns the same `11000000` error, I have one other idea to try

**Comment by pschroeder89** [comment]
I made similar changes to all of the other accessories, please let me know what works and what doesn't with 1.8.9-beta.7. Thanks!

**Comment by vernlazaro** [comment]
Sleep works now but Display and Power get the 11000000 error.

1/26/2023, 3:22:39 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setDisplay to Humidifier LR with ({"screenSwitch":false,"id":0})! Response: {"traceId":"1674764559652","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674764559652","code":11000000}}
[1/26/2023, 3:22:43 PM] [Levoit Humidifiers] Setting Display to true
[1/26/2023, 3:22:43 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setDisplay to Humidifier LR with ({"screenSwitch":true,"id":0})...
[1/26/2023, 3:22:43 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setDisplay to Humidifier LR with ({"screenSwitch":true,"id":0})! Response: {"traceId":"1674764563238","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674764563238","code":11000000}}

[1/26/2023, 3:23:34 PM] [Levoit Humidifiers] Setting Power to false
[1/26/2023, 3:23:34 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setSwitch to Humidifier LR with ({"powerSwitch":false,"id":0})...
[1/26/2023, 3:23:34 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setSwitch to Humidifier LR with ({"powerSwitch":false,"id":0})! Response: {"traceId":"1674764614639","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674764614639","code":11000000}}
[1/26/2023, 3:23:36 PM] [Levoit Humidifiers] Setting Power to true
[1/26/2023, 3:23:36 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setSwitch to Humidifier LR with ({"powerSwitch":true,"id":0})...
[1/26/2023, 3:23:36 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setSwitch to Humidifier LR with ({"powerSwitch":true,"id":0})! Response: {"traceId":"1674764616798","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674764616798","code":11000000}}

**Comment by pschroeder89** [comment]
Beta 9 is up with potential fixes for both

**Comment by vernlazaro** [comment]
Awesome! Everything looks to be working. 

Thanks!

**Comment by pschroeder89** [comment]
Great! Does the cool mist slider work correctly too? Could you send me a log after moving the slider? Just want to make sure we are getting the right response. Thanks!

**Comment by vernlazaro** [comment]
The Mist Slider is getting the 11000000 error when moved up/down.

1/26/2023, 4:07:13 PM] [Levoit Humidifiers] Setting Mist Level to 2
[1/26/2023, 4:07:14 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setSwitch to Humidifier LR with ({"powerSwitch":1,"id":0})! Response: {"traceId":"1674767233849","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674767233849","code":0}}
[1/26/2023, 4:07:14 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"virtualLevel":2,"type":"mist","id":0})...
[1/26/2023, 4:07:14 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"virtualLevel":2,"type":"mist","id":0})! Response: {"traceId":"1674767234259","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674767234259","code":11000000}}
[1/26/2023, 4:07:14 PM] [Levoit Humidifiers] Setting Mist Level to 3
[1/26/2023, 4:07:14 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"virtualLevel":3,"type":"mist","id":0})...
[1/26/2023, 4:07:14 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"virtualLevel":3,"type":"mist","id":0})! Response: {"traceId":"1674767234351","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674767234351","code":11000000}}
[1/26/2023, 4:07:21 PM] [Levoit Humidifiers] Setting Mist Level to 2
[1/26/2023, 4:07:21 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"virtualLevel":2,"type":"mist","id":0})...
[1/26/2023, 4:07:22 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"virtualLevel":2,"type":"mist","id":0})! Response: {"traceId":"1674767241928","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674767241928","code":11000000}}

**Comment by pschroeder89** [comment]
Beta 10 is published with a possible fix. If that doesn't work, I have 1 or 2 other things I will try

**Comment by vernlazaro** [comment]
Still the same:
powerSwitch":1,"id":0})...
[1/26/2023, 4:19:10 PM] [Levoit Humidifiers] Setting Mist Level to 2
[1/26/2023, 4:19:10 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setSwitch to Humidifier LR with ({"powerSwitch":1,"id":0})! Response: {"traceId":"1674767950108","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674767950108","code":0}}
[1/26/2023, 4:19:10 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"virtualLevel":2,"id":0})...
[1/26/2023, 4:19:10 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"virtualLevel":2,"id":0})! Response: {"traceId":"1674767950258","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674767950258","code":11000000}}
[1/26/2023, 4:19:10 PM] [Levoit Humidifiers] Setting Mist Level to 3
[1/26/2023, 4:19:10 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"virtualLevel":3,"id":0})...
[1/26/2023, 4:19:10 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"virtualLevel":3,"id":0})! Response: {"traceId":"1674767950410","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674767950410","code":11000000}}
[1/26/2023, 4:19:14 PM] [Levoit Humidifiers] Setting Mist Level to 2
[1/26/2023, 4:19:14 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"virtualLevel":2,"id":0})...
[1/26/2023, 4:19:14 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"virtualLevel":2,"id":0})! Response: {"traceId":"1674767954830","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674767954830","code":11000000}}

**Comment by pschroeder89** [comment]
Beta 11 is up, trying a slightly different name of the field

**Comment by vernlazaro** [comment]
Same error:
[1/26/2023, 4:26:09 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":3,"type":"mist","id":0})...
[1/26/2023, 4:26:09 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":3,"type":"mist","id":0})! Response: {"traceId":"1674768369574","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674768369574","code":11000000}}
[1/26/2023, 4:26:13 PM] [Levoit Humidifiers] Setting Mist Level to 4
[1/26/2023, 4:26:13 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":4,"type":"mist","id":0})...
[1/26/2023, 4:26:13 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":4,"type":"mist","id":0})! Response: {"traceId":"1674768373583","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674768373583","code":11000000}}
[1/26/2023, 4:26:16 PM] [Levoit Humidifiers] Setting Mist Level to 3
[1/26/2023, 4:26:16 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":3,"type":"mist","id":0})...
[1/26/2023, 4:26:16 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":3,"type":"mist","id":0})! Response: {"traceId":"1674768376216","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674768376216","code":11000000}}
[1/26/2023, 4:26:16 PM] [Levoit Humidifiers] Setting Mist Level to 2
[1/26/2023, 4:26:16 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":2,"type":"mist","id":0})...
[1/26/2023, 4:26:16 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":2,"type":"mist","id":0})! Response: {"traceId":"1674768376440","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674768376440","code":11000000}}

**Comment by pschroeder89** [comment]
Beta 12 is pushed. If we can't figure it out, I will hide the cool slider for this model. I think most people use Auto / Sleep modes anyway, but it would be nice to get this working. Fingers crossed this change works

**Comment by vernlazaro** [comment]
Slider still doesn't work.

[1/26/2023, 4:36:38 PM] [Levoit Humidifiers] Setting Mist Level to 4
[1/26/2023, 4:36:38 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":4,"type":"mist","id":0})...
[1/26/2023, 4:36:39 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":4,"type":"mist","id":0})! Response: {"traceId":"1674768998961","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674768998961","code":11000000}}
[1/26/2023, 4:36:40 PM] [Levoit Humidifiers] Setting Mist Level to 2
[1/26/2023, 4:36:40 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":2,"type":"mist","id":0})...
[1/26/2023, 4:36:41 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":2,"type":"mist","id":0})! Response: {"traceId":"1674769000893","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674769000893","code":11000000}}
[1/26/2023, 4:36:56 PM] [Levoit Humidifiers] Setting Mist Level to 1
[1/26/2023, 4:36:56 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":1,"type":"mist","id":0})...
[1/26/2023, 4:36:56 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"mistVirtualLevel":1,"type":"mist","id":0})! Response: {"traceId":"1674769016730","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674769016730","code":11000000}}

**Comment by pschroeder89** [comment]
I think that last log is from the previous version, maybe a cached instance ...Could you restart homebridge and try again with beta 12?

**Comment by vernlazaro** [comment]
Still the same after restarting

1/26/2023, 4:45:00 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setSwitch to Humidifier LR with ({"powerSwitch":1,"id":0})! Response: {"traceId":"1674769500369","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674769500369","code":0}}
[1/26/2023, 4:45:00 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"level":5,"id":0})...
[1/26/2023, 4:45:00 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"level":5,"id":0})! Response: {"traceId":"1674769500555","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674769500555","code":11000000}}
[1/26/2023, 4:45:04 PM] [Levoit Humidifiers] Setting Mist Level to 3
[1/26/2023, 4:45:04 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"level":3,"id":0})...
[1/26/2023, 4:45:04 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"level":3,"id":0})! Response: {"traceId":"1674769504466","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674769504466","code":11000000}}
[1/26/2023, 4:45:07 PM] [Levoit Humidifiers] Setting Mist Level to 4
[1/26/2023, 4:45:07 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setVirtualLevel to Humidifier LR with ({"level":4,"id":0})...
[1/26/2023, 4:45:07 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setVirtualLevel to Humidifier LR with ({"level":4,"id":0})! Response: {"traceId":"1674769507642","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674769507642","code":11000000}}

**Comment by pschroeder89** [comment]
Published beta 13, trying to send the command using another method (which we use to send warm level controls on other models). If this doesn't work, beta 14 will be the removal of the slider. Thanks again for testing!

**Comment by vernlazaro** [comment]
Still the same:

[1/26/2023, 5:29:21 PM] [Levoit Humidifiers] Setting Mist Level to 4
[1/26/2023, 5:29:21 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setSwitch to Humidifier LR with ({"powerSwitch":1,"id":0})! Response: {"traceId":"1674772161571","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674772161571","code":0}}
[1/26/2023, 5:29:21 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setLevel to Humidifier LR with ({"level":4,"type":"mist","id":0})...
[1/26/2023, 5:29:21 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setLevel to Humidifier LR with ({"level":4,"type":"mist","id":0})! Response: {"traceId":"1674772161662","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674772161662","code":11000000}}
[1/26/2023, 5:29:21 PM] [Levoit Humidifiers] Setting Mist Level to 3
[1/26/2023, 5:29:21 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setLevel to Humidifier LR with ({"level":3,"type":"mist","id":0})...
[1/26/2023, 5:29:21 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setLevel to Humidifier LR with ({"level":3,"type":"mist","id":0})! Response: {"traceId":"1674772161750","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674772161750","code":11000000}}
[1/26/2023, 5:29:24 PM] [Levoit Humidifiers] Setting Mist Level to 4
[1/26/2023, 5:29:24 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Sending command setLevel to Humidifier LR with ({"level":4,"type":"mist","id":0})...
[1/26/2023, 5:29:24 PM] [Levoit Humidifiers] [DEBUG]: [SEND COMMAND] Successfully sent command setLevel to Humidifier LR with ({"level":4,"type":"mist","id":0})! Response: {"traceId":"1674772164213","code":0,"msg":"request success","module":null,"stacktrace":null,"result":{"traceId":"1674772164213","code":11000000}}

**Comment by pschroeder89** [comment]
beta 14 is pushed. the mist slider should no longer be visible and the other accessories should work.

**Comment by vernlazaro** [comment]
Yes, the Mist Slider is no longer displayed. The power, display and sleep mode controls all work.  Thanks!

**Comment by pschroeder89** [comment]
Awesome, thanks for all of your help! Hopefully someone figures out the cool mist request soon. I've published 1.9.0 non-beta for public release. Closing this issue.
